/* eslint-disable max-len */
export const sampleDowRequest = {
  documentType: "DESCRIPTION_OF_WORK_DOCX",
  templatePayload: {
    awardHistory: [
      {
        contractAwardType: "INITIAL_AWARD",
        modificationOrder: null,
        effectiveDate: "2023-01-01",
      },
    ],
    contractInformation: [
      {
        currentContractExists: true,
        contractNumber: "349759340",
        contractExpirationDate: "2023-12-28",
        incumbentContractorName: "Random Person",
        taskDeliveryOrderNumber: "ABC123",
      },
      {
        currentContractExists: false,
        contractNumber: "359875605",
        contractExpirationDate: "2022-02-28",
        incumbentContractorName: "Random Person",
        taskDeliveryOrderNumber: "DEF456",
      },
    ],
    toTitle: "Test Package for DOW",
    scope: "Using as a way to see where different sections are saving information.",
    surgeRequirementCapacity: 44,
    surgeRequirementCapabilities: true,
    currentEnvironment: {
      currentEnvironmentExists: true,
      hasSystemDocumentation: false,
      hasMigrationDocumentation: false,
      envLocation: "CLOUD",
      envClassificationsCloud: [
        {
          classification: "S",
          display: "Secret - IL6",
          impactLevel: "IL6",
        },
        {
          classification: "U",
          display: "Unclassified - IL2",
          impactLevel: "IL2",
        },
        {
          classification: "U",
          display: "Unclassified - IL5",
          impactLevel: "IL5",
        },
      ],
      envClassificationsOnprem: [],
      envInstances: [
        {
          instanceName: null,
          instanceLocation: "CLOUD",
          numberOfInstances: 4,
          usageDescription: null,
          anticipatedNeedOrUsage: null,
          operatingSystem: "Kali",
          operatingSystemLicensing: null,
          licensing: "MIT",
          region: null,
          needForEntireTaskOrderDuration: true,
          selectedPeriods: null,
          classificationLevel: {
            classification: "S",
            display: "Secret - IL6",
            impactLevel: "IL6",
          },
          classifiedInformationTypes: [],
          dataEgressMonthlyAmount: 985,
          dataEgressMonthlyUnit: "TB",
          memoryAmount: 64,
          memoryUnit: "GB",
          storageAmount: 2354,
          storageUnit: "TB",
          storageType: "ARCHIVE",
          numberOfVcpus: 100,
          performanceTier: "COMPUTE",
          processorSpeed: 250,
          pricingModel: "PAY_AS_YOU_GO",
          pricingModelExpiration: null,
          environmentType: null,
          operatingEnvironment: null,
          deployedRegions: [
            {
              name: "EUCOM",
              description: "United States European Command",
              sequence: 6,
              group: "OCONUS",
            },
          ],
          usersPerRegion: [
            {
              EUCOM: "8,755",
            },
          ],
          isTrafficSpikeEventBased: false,
          trafficSpikeEventDescription: null,
          isTrafficSpikePeriodBased: false,
          trafficSpikePeriodDescription: null,
          additionalInformation: "Cyber security geared.",
          currentUsageDescription: "EVEN_USAGE",
          anticipatedNeedUsage: null,
        },
        {
          instanceName: null,
          instanceLocation: "CLOUD",
          numberOfInstances: 4,
          usageDescription: null,
          anticipatedNeedOrUsage: null,
          operatingSystem: "Kali",
          operatingSystemLicensing: null,
          licensing: "MIT",
          region: null,
          needForEntireTaskOrderDuration: true,
          selectedPeriods: null,
          classificationLevel: {
            classification: "TS",
            display: "Top Secret",
            impactLevel: null,
          },
          classifiedInformationTypes: [],
          dataEgressMonthlyAmount: 985,
          dataEgressMonthlyUnit: "TB",
          memoryAmount: 64,
          memoryUnit: "GB",
          storageAmount: 2354,
          storageUnit: "TB",
          storageType: "ARCHIVE",
          numberOfVcpus: 100,
          performanceTier: "COMPUTE",
          processorSpeed: 250,
          pricingModel: "PAY_AS_YOU_GO",
          pricingModelExpiration: null,
          environmentType: null,
          operatingEnvironment: null,
          deployedRegions: [
            {
              name: "EUCOM",
              description: "United States European Command",
              sequence: 6,
              group: "OCONUS",
            },
          ],
          usersPerRegion: [
            {
              EUCOM: "8,755",
            },
          ],
          isTrafficSpikeEventBased: false,
          trafficSpikeEventDescription: null,
          isTrafficSpikePeriodBased: false,
          trafficSpikePeriodDescription: null,
          additionalInformation: "Cyber security geared.",
          currentUsageDescription: "EVEN_USAGE",
          anticipatedNeedUsage: null,
        },
        {
          instanceName: null,
          instanceLocation: "CLOUD",
          numberOfInstances: 5,
          usageDescription: null,
          anticipatedNeedOrUsage: null,
          operatingSystem: "Unknown",
          operatingSystemLicensing: null,
          licensing: "MIT",
          region: null,
          needForEntireTaskOrderDuration: true,
          selectedPeriods: null,
          classificationLevel: {
            classification: "U",
            display: "Unclassified - IL5",
            impactLevel: "IL5",
          },
          classifiedInformationTypes: [],
          dataEgressMonthlyAmount: 102394,
          dataEgressMonthlyUnit: "TB",
          memoryAmount: 2357,
          memoryUnit: "GB",
          storageAmount: 77,
          storageUnit: "TB",
          storageType: "OBJECT",
          numberOfVcpus: 88,
          performanceTier: "STORAGE",
          processorSpeed: 723,
          pricingModel: "PREPAID",
          pricingModelExpiration: "2023-02-28",
          environmentType: null,
          operatingEnvironment: null,
          deployedRegions: [
            {
              name: "CONUS Central",
              description: "Central Continental United States",
              sequence: 2,
              group: "CONUS",
            },
            {
              name: "AFRICOM",
              description: "United States Africa Command",
              sequence: 4,
              group: "OCONUS",
            },
          ],
          usersPerRegion: [
            {
              "CONUS Central": "19,238",
            },
            {
              AFRICOM: "13,939",
            },
          ],
          isTrafficSpikeEventBased: true,
          trafficSpikeEventDescription: "Black Friday",
          isTrafficSpikePeriodBased: true,
          trafficSpikePeriodDescription: "Winter and Spring",
          additionalInformation: "Looking to have something similar in the new system if not better.",
          currentUsageDescription: "IRREGULAR_USAGE",
          anticipatedNeedUsage: null,
        },
        {
          instanceName: null,
          instanceLocation: "CLOUD",
          numberOfInstances: 3,
          usageDescription: null,
          anticipatedNeedOrUsage: null,
          operatingSystem: "Mint",
          operatingSystemLicensing: null,
          licensing: "MIT",
          region: null,
          needForEntireTaskOrderDuration: true,
          selectedPeriods: null,
          classificationLevel: {
            classification: "U",
            display: "Unclassified - IL2",
            impactLevel: "IL2",
          },
          classifiedInformationTypes: [],
          dataEgressMonthlyAmount: 3945,
          dataEgressMonthlyUnit: "TB",
          memoryAmount: 124,
          memoryUnit: "GB",
          storageAmount: 500,
          storageUnit: "TB",
          storageType: "BLOCK",
          numberOfVcpus: 24,
          performanceTier: "GENERAL",
          processorSpeed: 8,
          pricingModel: "PAY_AS_YOU_GO",
          pricingModelExpiration: null,
          environmentType: null,
          operatingEnvironment: null,
          deployedRegions: [
            {
              name: "CONUS West",
              description: "Western Continental United States",
              sequence: 3,
              group: "CONUS",
            },
            {
              name: "CONUS East",
              description: "Eastern Continental United States",
              sequence: 1,
              group: "CONUS",
            },
            {
              name: "SOUTHCOM",
              description: "United States Southern Command",
              sequence: 8,
              group: "OCONUS",
            },
          ],
          usersPerRegion: [
            {
              "CONUS West": "4,305",
            },
            {
              "CONUS East": "2,345",
            },
            {
              SOUTHCOM: "5,278",
            },
          ],
          isTrafficSpikeEventBased: false,
          trafficSpikeEventDescription: null,
          isTrafficSpikePeriodBased: false,
          trafficSpikePeriodDescription: null,
          additionalInformation: "Some additional info here.",
          currentUsageDescription: "EVEN_USAGE",
          anticipatedNeedUsage: null,
        },
      ],
      additionalGrowth: true,
      anticipatedYearlyAdditionalCapacity: 14,
      currentEnvironmentReplicatedOptimized: "YES_OPTIMIZE",
      statementReplicatedOptimized:
        "The system was built in a rush, we are looking to optimize it to perform better and use less resources",
      hasPhasedApproach: true,
      phasedApproachSchedule: "B - 10, OP1- 23, OP2 -30, OP3 -35",
      needsArchitecturalDesignServices: true,
      architecturalDesignRequirement: {
        designIL2: {
          statement: "some statement",
          applicationsNeedingDesign: "application1",
          source: "DOW",
          externalFactors: "some external Factors",
          classificationLevel: [
            {
              classification: "U",
              display: "Unclassified - IL2",
              impactLevel: "IL2",
            },
          ],
        },
        designIL4: {
          statement: "some statementIL4",
          applicationsNeedingDesign: "application2",
          source: "DOW",
          externalFactors: "some external Factors",
          classificationLevel: [
            {
              classification: "U",
              display: "Unclassified - IL4",
              impactLevel: "IL4",
            },
          ],
        },
        designIL5: null,
        designIL6: {
          statement: "some statementIL6",
          applicationsNeedingDesign: "application2",
          source: "DOW",
          externalFactors: "some external Factors",
          classificationLevel: [
            {
              classification: "S",
              display: "Unclassified - IL6",
              impactLevel: "IL6",
            },
          ],
        },
        designTS: {
          statement: "some statement7",
          applicationsNeedingDesign: "application2",
          source: "DOW",
          externalFactors: "some external Factors",
          classificationLevel: [
            {
              classification: "TS",
              display: "Top Secret",
              impactLevel: null,
            },
          ],
        },
      },
    },
    selectedClassificationLevels: [
      {
        classificationLevel: {
          classification: "U",
          display: "Unclassified - IL2",
          impactLevel: "IL2",
        },
        classifiedInformationTypes: [],
        dataEgressMonthlyAmount: 34904,
        dataEgressMonthlyUnit: "GB",
        usersPerRegion: [
          {
            "CONUS West": "50,000",
          },
          {
            "CONUS East": "75,000",
          },
          {
            SOUTHCOM: "100,000",
          },
        ],
        dataIncrease: true,
        userGrowthEstimatePercentage: [5, 15, 22, 25],
        userGrowthEstimateType: "MULTIPLE",
        dataGrowthEstimatePercentage: [27],
        dataGrowthEstimateType: "SINGLE",
        usersIncrease: true,
      },
      {
        classificationLevel: {
          classification: "U",
          display: "Unclassified - IL5",
          impactLevel: "IL5",
        },
        classifiedInformationTypes: [],
        dataEgressMonthlyAmount: 1023,
        dataEgressMonthlyUnit: "PB",
        usersPerRegion: [
          {
            SOUTHCOM: "76,000",
          },
          {
            "CONUS West": "123,000",
          },
        ],
        dataIncrease: false,
        userGrowthEstimatePercentage: [5],
        userGrowthEstimateType: "SINGLE",
        dataGrowthEstimatePercentage: [],
        dataGrowthEstimateType: null,
        usersIncrease: true,
      },
      {
        classificationLevel: {
          classification: "S",
          display: "Secret - IL6",
          impactLevel: "IL6",
        },
        classifiedInformationTypes: [
          {
            name: "Restricted Data",
            description: null,
            sequence: 2,
          },
          {
            name: "National Intelligence Information: Non-SCI",
            description: null,
            sequence: 6,
          },
          {
            name: "North Atlantic Treaty Organization (NATO) Information",
            description: null,
            sequence: 8,
          },
          {
            name: "Foreign Government Information (FGI)",
            description: null,
            sequence: 9,
          },
        ],
        dataEgressMonthlyAmount: null,
        dataEgressMonthlyUnit: null,
        usersPerRegion: [
          {
            EUCOM: "200,000",
          },
        ],
        dataIncrease: false,
        userGrowthEstimatePercentage: [],
        userGrowthEstimateType: null,
        dataGrowthEstimatePercentage: [],
        dataGrowthEstimateType: null,
        usersIncrease: false,
      },
      {
        classificationLevel: {
          classification: "TS",
          display: "Top Secret",
          impactLevel: null,
        },
        classifiedInformationTypes: [
          {
            name: "Restricted Data",
            description: null,
            sequence: 2,
            acronym: "RD",
          },
          {
            name: "Foreign Government Information (FGI)",
            description: null,
            sequence: 6,
            acronym: "FGI",
          },
          {
            name: "Special Access Program (SAP) Information",
            description: null,
            sequence: 6,
            acronym: "SAP",
          },
        ],
        dataEgressMonthlyAmount: null,
        dataEgressMonthlyUnit: null,
        usersPerRegion: [
          {
            EUCOM: "200,000",
          },
        ],
        dataIncrease: false,
        userGrowthEstimatePercentage: [],
        userGrowthEstimateType: null,
        dataGrowthEstimatePercentage: [],
        dataGrowthEstimateType: null,
        usersIncrease: false,
      },
    ],
    architecturalDesignRequirement: {
      designIL2: {
        statement: "some statement",
        applicationsNeedingDesign: "application1",
        source: "DOW",
        externalFactors: "some external Factors",
        classificationLevel: [
          {
            classification: "U",
            display: "Unclassified - IL2",
            impactLevel: "IL2",
          },
        ],
      },
      designIL4: {
        statement: "some statementIL4",
        applicationsNeedingDesign: "application2",
        source: "DOW",
        externalFactors: "some external Factors",
        classificationLevel: [
          {
            classification: "U",
            display: "Unclassified - IL4",
            impactLevel: "IL4",
          },
        ],
      },
      designIL5: null,
      designIL6: {
        statement: "some statementIL6",
        applicationsNeedingDesign: "application2",
        source: "DOW",
        externalFactors: "some external Factors",
        classificationLevel: [
          {
            classification: "S",
            display: "Unclassified - IL6",
            impactLevel: "IL6",
          },
        ],
      },
      designTS: {
        statement: "some statement7",
        applicationsNeedingDesign: "application2",
        source: "DOW",
        externalFactors: "some external Factors",
        classificationLevel: [
          {
            classification: "TS",
            display: "Top Secret",
            impactLevel: null,
          },
        ],
      },
    },
    xaasOfferings: {
      selectedServiceInstances: [
        {
          classificationInstances: [
            {
              classificationLevel: {
                classification: "U",
                display: "Unclassified - IL5",
                impactLevel: "IL5",
              },
              classifiedInformationTypes: [],
              selectedPeriods: null,
              needForEntireTaskOrderDuration: true,
              usageDescription: "Web app - limited ",
              typeOfDelivery: null,
              typeOfMobility: null,
              typeOfMobilityOther: null,
              tsContractorClearanceType: null,
            },
            {
              classificationLevel: {
                classification: "S",
                display: "Secret - IL6",
                impactLevel: "IL6",
              },
              classifiedInformationTypes: [],
              selectedPeriods: null,
              needForEntireTaskOrderDuration: true,
              usageDescription: "Web app - a need to know basis",
              typeOfDelivery: null,
              typeOfMobility: null,
              typeOfMobilityOther: null,
              tsContractorClearanceType: null,
            },
          ],
          otherServiceOffering: null,
          serviceOffering: {
            name: "Web app",
            description: null,
            serviceOfferingGroup: "APPLICATIONS",
            sequence: 2,
          },
        },
        {
          classificationInstances: [
            {
              classificationLevel: {
                classification: "U",
                display: "Unclassified - IL2",
                impactLevel: "IL2",
              },
              classifiedInformationTypes: [],
              selectedPeriods: null,
              needForEntireTaskOrderDuration: true,
              usageDescription: "DB server  - public",
              typeOfDelivery: null,
              typeOfMobility: null,
              typeOfMobilityOther: null,
              tsContractorClearanceType: null,
            },
            {
              classificationLevel: {
                classification: "U",
                display: "Unclassified - IL5",
                impactLevel: "IL5",
              },
              classifiedInformationTypes: [],
              selectedPeriods: null,
              needForEntireTaskOrderDuration: true,
              usageDescription: "DB server  - limited",
              typeOfDelivery: null,
              typeOfMobility: null,
              typeOfMobilityOther: null,
              tsContractorClearanceType: null,
            },
            {
              classificationLevel: {
                classification: "S",
                display: "Secret - IL6",
                impactLevel: "IL6",
              },
              classifiedInformationTypes: [],
              selectedPeriods: null,
              needForEntireTaskOrderDuration: true,
              usageDescription: "DB server  - need to know basis",
              typeOfDelivery: null,
              typeOfMobility: null,
              typeOfMobilityOther: null,
              tsContractorClearanceType: null,
            },
          ],
          otherServiceOffering: null,
          serviceOffering: {
            name: "Database",
            description: null,
            serviceOfferingGroup: "APPLICATIONS",
            sequence: 3,
          },
        },
        {
          classificationInstances: [
            {
              classificationLevel: {
                classification: "U",
                display: "Unclassified - IL2",
                impactLevel: "IL2",
              },
              classifiedInformationTypes: [],
              selectedPeriods: null,
              needForEntireTaskOrderDuration: true,
              usageDescription: "Automation and security best practice",
              typeOfDelivery: null,
              typeOfMobility: null,
              typeOfMobilityOther: null,
              tsContractorClearanceType: null,
            },
            {
              classificationLevel: {
                classification: "S",
                display: "Secret - IL6",
                impactLevel: "IL6",
              },
              classifiedInformationTypes: [],
              selectedPeriods: null,
              needForEntireTaskOrderDuration: true,
              usageDescription: "Keeping",
              typeOfDelivery: null,
              typeOfMobility: null,
              typeOfMobilityOther: null,
              tsContractorClearanceType: null,
            },
          ],
          otherServiceOffering: null,
          serviceOffering: {
            name: "DevSecOps",
            description: null,
            serviceOfferingGroup: "DEVELOPER_TOOLS",
            sequence: 1,
          },
        },
        {
          classificationInstances: [
            {
              classificationLevel: {
                classification: "U",
                display: "Unclassified - IL2",
                impactLevel: "IL2",
              },
              classifiedInformationTypes: [],
              selectedPeriods: null,
              needForEntireTaskOrderDuration: true,
              usageDescription: "Need TE for at edge",
              typeOfDelivery: "SHIPPED",
              typeOfMobility: "MODULAR",
              typeOfMobilityOther: null,
              tsContractorClearanceType: null,
            },
          ],
          otherServiceOffering: null,
          serviceOffering: {
            name: "Mobility",
            description: null,
            serviceOfferingGroup: "EDGE_COMPUTING",
            sequence: 1,
          },
        },
        {
          classificationInstances: [
            {
              classificationLevel: {
                classification: "S",
                display: "Secret - IL6",
                impactLevel: "IL6",
              },
              classifiedInformationTypes: [
                {
                  name: "EDGE Computing Classified Info Type - Secret",
                  description: "If CNWDI access is required, then Restricted Data must also be selected.",
                  sequence: 3,
                },
              ],
              selectedPeriods: null,
              needForEntireTaskOrderDuration: true,
              usageDescription: "Need TE for at edge",
              typeOfDelivery: "SHIPPED",
              typeOfMobility: "MODULAR",
              typeOfMobilityOther: null,
              tsContractorClearanceType: null,
            },
          ],
          otherServiceOffering: null,
          serviceOffering: {
            name: "Mobility",
            description: null,
            serviceOfferingGroup: "EDGE_COMPUTING",
            sequence: 1,
          },
        },
        {
          classificationInstances: [
            {
              classificationLevel: {
                classification: "TS",
                display: "Top Secret",
                impactLevel: null,
              },
              classifiedInformationTypes: [
                {
                  name: "EDGE Computing Classified Info Type - Top Secret",
                  description: "If CNWDI access is required, then Restricted Data must also be selected.",
                  sequence: 3,
                },
              ],
              selectedPeriods: null,
              needForEntireTaskOrderDuration: true,
              usageDescription: "Need TE for at edge",
              typeOfDelivery: "SHIPPED",
              typeOfMobility: "MODULAR",
              typeOfMobilityOther: null,
              tsContractorClearanceType: "TS_SCI",
            },
          ],
          otherServiceOffering: null,
          serviceOffering: {
            name: "Mobility",
            description: null,
            serviceOfferingGroup: "EDGE_COMPUTING",
            sequence: 1,
          },
        },
        {
          classificationInstances: [
            {
              classificationLevel: {
                classification: "U",
                display: "Unclassified - IL2",
                impactLevel: "IL2",
              },
              classifiedInformationTypes: [],
              selectedPeriods: null,
              needForEntireTaskOrderDuration: true,
              usageDescription: "web server",
              typeOfDelivery: null,
              typeOfMobility: null,
              typeOfMobilityOther: null,
              tsContractorClearanceType: null,
            },
            {
              classificationLevel: {
                classification: "U",
                display: "Unclassified - IL5",
                impactLevel: "IL5",
              },
              classifiedInformationTypes: [],
              selectedPeriods: null,
              needForEntireTaskOrderDuration: true,
              usageDescription: "app server",
              typeOfDelivery: null,
              typeOfMobility: null,
              typeOfMobilityOther: null,
              tsContractorClearanceType: null,
            },
            {
              classificationLevel: {
                classification: "S",
                display: "Secret - IL6",
                impactLevel: "IL6",
              },
              classifiedInformationTypes: [],
              selectedPeriods: [
                {
                  periodType: "OPTION",
                  periodUnitCount: 34,
                  periodUnit: "WEEK",
                  optionOrder: 2,
                },
                {
                  periodType: "OPTION",
                  periodUnitCount: 8,
                  periodUnit: "MONTH",
                  optionOrder: 3,
                },
                {
                  periodType: "OPTION",
                  periodUnitCount: 1,
                  periodUnit: "YEAR",
                  optionOrder: 4,
                },
              ],
              needForEntireTaskOrderDuration: false,
              usageDescription: "db server",
              typeOfDelivery: null,
              typeOfMobility: null,
              typeOfMobilityOther: null,
              tsContractorClearanceType: null,
            },
          ],
          otherServiceOffering: null,
          serviceOffering: {
            name: "Application",
            description: null,
            serviceOfferingGroup: "APPLICATIONS",
            sequence: 1,
          },
        },
      ],
      computeInstances: [
        {
          instanceName: null,
          instanceLocation: null,
          numberOfInstances: 4,
          usageDescription: null,
          anticipatedNeedOrUsage: "preparing and testing",
          operatingSystem: "Red Hat",
          operatingSystemLicensing: "TRANSFER_EXISTING",
          licensing: null,
          region: null,
          needForEntireTaskOrderDuration: false,
          selectedPeriods: [
            {
              periodType: "OPTION",
              periodUnitCount: 34,
              periodUnit: "WEEK",
              optionOrder: 2,
            },
            {
              periodType: "OPTION",
              periodUnitCount: 8,
              periodUnit: "MONTH",
              optionOrder: 3,
            },
          ],
          classificationLevel: {
            classification: "U",
            display: "Unclassified - IL5",
            impactLevel: "IL5",
          },
          classifiedInformationTypes: [],
          dataEgressMonthlyAmount: null,
          dataEgressMonthlyUnit: null,
          memoryAmount: 495,
          memoryUnit: "GB",
          storageAmount: 500,
          storageUnit: "GB",
          storageType: "BLOCK",
          numberOfVcpus: 334,
          performanceTier: "COMPUTE",
          processorSpeed: 38,
          pricingModel: null,
          pricingModelExpiration: null,
          environmentType: "PRE_PROD",
          operatingEnvironment: "SERVERLESS",
        },
        {
          instanceName: null,
          instanceLocation: null,
          numberOfInstances: 3,
          usageDescription: null,
          anticipatedNeedOrUsage: "Need this as base for platform",
          operatingSystem: "Imagine",
          operatingSystemLicensing: "NEW",
          licensing: null,
          region: null,
          needForEntireTaskOrderDuration: true,
          selectedPeriods: null,
          classificationLevel: {
            classification: "U",
            display: "Unclassified - IL2",
            impactLevel: "IL2",
          },
          classifiedInformationTypes: [],
          dataEgressMonthlyAmount: null,
          dataEgressMonthlyUnit: null,
          memoryAmount: 233,
          memoryUnit: "GB",
          storageAmount: 545,
          storageUnit: "PB",
          storageType: "BLOCK",
          numberOfVcpus: 848,
          performanceTier: "GENERAL",
          processorSpeed: 235,
          pricingModel: null,
          pricingModelExpiration: null,
          environmentType: "DEV_TEST",
          operatingEnvironment: "VIRTUAL",
        },
        {
          instanceName: null,
          instanceLocation: null,
          numberOfInstances: 10,
          usageDescription: null,
          anticipatedNeedOrUsage: "Going live",
          operatingSystem: "Unicorn",
          operatingSystemLicensing: "NEW",
          licensing: null,
          region: null,
          needForEntireTaskOrderDuration: true,
          selectedPeriods: null,
          classificationLevel: {
            classification: "S",
            display: "Secret - IL6",
            impactLevel: "IL6",
          },
          classifiedInformationTypes: [],
          dataEgressMonthlyAmount: null,
          dataEgressMonthlyUnit: null,
          memoryAmount: 677,
          memoryUnit: "GB",
          storageAmount: 1500,
          storageUnit: "PB",
          storageType: "FILE",
          numberOfVcpus: 555,
          performanceTier: "COMPUTE",
          processorSpeed: 999,
          pricingModel: null,
          pricingModelExpiration: null,
          environmentType: "PROD_STAGING",
          operatingEnvironment: "VIRTUAL",
        },
      ],
      databaseInstances: [
        {
          instanceName: null,
          instanceLocation: null,
          numberOfInstances: 3,
          usageDescription: null,
          anticipatedNeedOrUsage: "external DB",
          operatingSystem: "Linux",
          operatingSystemLicensing: null,
          licensing: "NEW",
          region: null,
          needForEntireTaskOrderDuration: true,
          selectedPeriods: null,
          classificationLevel: {
            classification: "S",
            display: "Secret - IL6",
            impactLevel: "IL6",
          },
          classifiedInformationTypes: [],
          dataEgressMonthlyAmount: null,
          dataEgressMonthlyUnit: null,
          memoryAmount: 99,
          memoryUnit: "GB",
          storageAmount: 99,
          storageUnit: "TB",
          storageType: "OBJECT",
          numberOfVcpus: 987,
          performanceTier: null,
          processorSpeed: 88,
          pricingModel: null,
          pricingModelExpiration: null,
          databaseLicensing: "NEW",
          databaseType: "TRANSACTIONAL",
          databaseTypeOther: null,
          networkPerformance: "1087",
        },
      ],
      storageInstances: [],
      generalInstances: [],
    },
    crossDomainSolutions: {
      anticipatedNeedOrUsage: "Need to move documents between classification based on a new law.",
      crossDomainSolutionRequired: true,
      selectedPeriods: [
        {
          periodType: "BASE",
          periodUnitCount: 1,
          periodUnit: "YEAR",
          optionOrder: 1,
        },
        {
          periodType: "OPTION",
          periodUnitCount: 34,
          periodUnit: "WEEK",
          optionOrder: 2,
        },
        {
          periodType: "OPTION",
          periodUnitCount: 8,
          periodUnit: "MONTH",
          optionOrder: 3,
        },
      ],
      needForEntireTaskOrderDuration: false,
      projectedFileStreamType: "PDF documents",
      trafficPerDomainPair: [
        {
          type: "U_TO_S",
          dataQuantity: 4039,
        },
        {
          type: "S_TO_U",
          dataQuantity: 235,
        },
        {
          type: "U_TO_TS",
          dataQuantity: 800,
        },
        {
          type: "S_TO_TS",
          dataQuantity: 100,
        },
        {
          type: "TS_TO_U",
          dataQuantity: 500,
        },
        {
          type: "TS_TO_S",
          dataQuantity: 750,
        },
      ],
    },
    cloudSupportPackages: [
      {
        instanceName: "Training #1",
        instanceLocation: null,
        numberOfInstances: 1,
        usageDescription: null,
        anticipatedNeedOrUsage: "train admins",
        operatingSystem: null,
        operatingSystemLicensing: null,
        licensing: null,
        region: null,
        needForEntireTaskOrderDuration: true,
        selectedPeriods: null,
        classificationLevel: {
          classification: "S",
          display: "Secret - IL6",
          impactLevel: "IL6",
        },
        classifiedInformationTypes: [
          {
            name: "Critical Nuclear Weapon Design Information (CNWDI)",
            description: "If CNWDI access is required, then Restricted Data must also be selected.",
            sequence: 3,
          },
        ],
        dataEgressMonthlyAmount: null,
        dataEgressMonthlyUnit: null,
        memoryAmount: null,
        memoryUnit: "GB",
        storageAmount: null,
        storageUnit: "GB",
        storageType: null,
        numberOfVcpus: null,
        performanceTier: null,
        processorSpeed: null,
        pricingModel: null,
        pricingModelExpiration: null,
        personnelOnsiteAccess: null,
        serviceType: "TRAINING",
        trainingRequirementTitle: null,
        trainingFormat: "ONSITE_INSTRUCTOR_CONUS",
        personnelRequiringTraining: 400,
        trainingFacilityType: "GOVERNMENT_FACILITY",
        trainingLocation: "DC",
        trainingTimeZone: null,
        canTrainInUnclassEnv: null,
        tsContractorClearanceType: null,
      },
      {
        instanceName: "Training #2 (TS)",
        instanceLocation: null,
        numberOfInstances: 1,
        usageDescription: null,
        anticipatedNeedOrUsage: "train admins",
        operatingSystem: null,
        operatingSystemLicensing: null,
        licensing: null,
        region: null,
        needForEntireTaskOrderDuration: true,
        selectedPeriods: null,
        classificationLevel: {
          classification: "TS",
          display: "Top Secret",
          impactLevel: null,
        },
        classifiedInformationTypes: [
          {
            name: "Top Secret info type - cloud support",
            description: "If CNWDI access is required, then Restricted Data must also be selected.",
            sequence: 3,
          },
        ],
        dataEgressMonthlyAmount: null,
        dataEgressMonthlyUnit: null,
        memoryAmount: null,
        memoryUnit: "GB",
        storageAmount: null,
        storageUnit: "GB",
        storageType: null,
        numberOfVcpus: null,
        performanceTier: null,
        processorSpeed: null,
        pricingModel: null,
        pricingModelExpiration: null,
        personnelOnsiteAccess: null,
        serviceType: "TRAINING",
        trainingRequirementTitle: null,
        trainingFormat: "ONSITE_INSTRUCTOR_CONUS",
        personnelRequiringTraining: 400,
        trainingFacilityType: "GOVERNMENT_FACILITY",
        trainingLocation: "DC",
        trainingTimeZone: null,
        canTrainInUnclassEnv: null,
        tsContractorClearanceType: "TS",
      },
      {
        instanceName: null,
        instanceLocation: null,
        numberOfInstances: 1,
        usageDescription: null,
        anticipatedNeedOrUsage: "On base help",
        operatingSystem: null,
        operatingSystemLicensing: null,
        licensing: null,
        region: null,
        needForEntireTaskOrderDuration: true,
        selectedPeriods: null,
        classificationLevel: {
          classification: "S",
          display: "Secret - IL6",
          impactLevel: "IL6",
        },
        classifiedInformationTypes: [
          {
            name: "Restricted Data",
            description: null,
            sequence: 2,
          },
          {
            name: "Formerly Restricted Data",
            description: null,
            sequence: 4,
          },
          {
            name: "Controlled Unclassified Information (CUI)",
            description: null,
            sequence: 11,
          },
        ],
        dataEgressMonthlyAmount: null,
        dataEgressMonthlyUnit: null,
        memoryAmount: null,
        memoryUnit: "GB",
        storageAmount: null,
        storageUnit: "GB",
        storageType: null,
        numberOfVcpus: null,
        performanceTier: null,
        processorSpeed: null,
        pricingModel: null,
        pricingModelExpiration: null,
        personnelOnsiteAccess: true,
        serviceType: "ADVISORY_ASSISTANCE",
        trainingRequirementTitle: null,
        trainingFormat: null,
        personnelRequiringTraining: null,
        trainingFacilityType: null,
        trainingLocation: null,
        trainingTimeZone: null,
        canTrainInUnclassEnv: null,
        tsContractorClearanceType: null,
      },
      {
        instanceName: null,
        instanceLocation: null,
        numberOfInstances: 1,
        usageDescription: null,
        anticipatedNeedOrUsage: "doc assistance for transferring things",
        operatingSystem: null,
        operatingSystemLicensing: null,
        licensing: null,
        region: null,
        needForEntireTaskOrderDuration: true,
        selectedPeriods: null,
        classificationLevel: {
          classification: "U",
          display: "Unclassified - IL5",
          impactLevel: "IL5",
        },
        classifiedInformationTypes: [],
        dataEgressMonthlyAmount: null,
        dataEgressMonthlyUnit: null,
        memoryAmount: null,
        memoryUnit: "GB",
        storageAmount: null,
        storageUnit: "GB",
        storageType: null,
        numberOfVcpus: null,
        performanceTier: null,
        processorSpeed: null,
        pricingModel: null,
        pricingModelExpiration: null,
        personnelOnsiteAccess: false,
        serviceType: "DOCUMENTATION_SUPPORT",
        trainingRequirementTitle: null,
        trainingFormat: null,
        personnelRequiringTraining: null,
        trainingFacilityType: null,
        trainingLocation: null,
        trainingTimeZone: null,
        canTrainInUnclassEnv: null,
        tsContractorClearanceType: null,
      },
      {
        instanceName: null,
        instanceLocation: null,
        numberOfInstances: 1,
        usageDescription: null,
        anticipatedNeedOrUsage: null,
        operatingSystem: null,
        operatingSystemLicensing: null,
        licensing: null,
        region: null,
        needForEntireTaskOrderDuration: true,
        selectedPeriods: null,
        classificationLevel: {
          classification: "U",
          display: "Unclassified - IL5",
          impactLevel: "IL5",
        },
        classifiedInformationTypes: [],
        dataEgressMonthlyAmount: null,
        dataEgressMonthlyUnit: null,
        memoryAmount: null,
        memoryUnit: "GB",
        storageAmount: null,
        storageUnit: "GB",
        storageType: null,
        numberOfVcpus: null,
        performanceTier: null,
        processorSpeed: null,
        pricingModel: null,
        pricingModelExpiration: null,
        personnelOnsiteAccess: null,
        serviceType: "PORTABILITY_PLAN",
        trainingRequirementTitle: null,
        trainingFormat: null,
        personnelRequiringTraining: null,
        trainingFacilityType: null,
        trainingLocation: null,
        trainingTimeZone: null,
        canTrainInUnclassEnv: null,
        tsContractorClearanceType: null,
      },
    ],
    contractType: {
      firmFixedPrice: true,
      timeAndMaterials: false,
      contractTypeJustification: "",
    },
    periodOfPerformance: {
      basePeriod: {
        periodType: "BASE",
        periodUnitCount: 1,
        periodUnit: "YEAR",
        optionOrder: 1,
      },
      isRequirementFollowOnProcurementSoleSourced: true,
      optionPeriods: [
        {
          periodType: "OPTION",
          periodUnitCount: 34,
          periodUnit: "WEEK",
          optionOrder: 2,
        },
        {
          periodType: "OPTION",
          periodUnitCount: 8,
          periodUnit: "MONTH",
          optionOrder: 3,
        },
        {
          periodType: "OPTION",
          periodUnitCount: 1,
          periodUnit: "YEAR",
          optionOrder: 4,
        },
      ],
      popStartRequest: true,
      requestedPopStartDate: "2023-03-01",
      timeFrame: "NO_SOONER_THAN",
      recurringRequirement: false,
    },
    securityRequirements: [],
    contractConsiderations: {
      potentialConflictOfInterest: false,
      conflictOfInterestExplanation: "",
      packagingShippingNoneApply: false,
      packagingShippingOther: true,
      packagingShippingOtherExplanation: "Door to door by team member.",
      contractorProvidedTransfer: true,
      piiPresent: true,
      systemOfRecordName: "NCEES Records",
      travel: [
        {
          durationInDays: 5,
          numberOfTravelers: 4,
          numberOfTrips: 8,
          selectedPeriods: [
            {
              periodType: "BASE",
              periodUnitCount: 1,
              periodUnit: "YEAR",
              optionOrder: 1,
            },
            {
              periodType: "OPTION",
              periodUnitCount: 34,
              periodUnit: "WEEK",
              optionOrder: 2,
            },
            {
              periodType: "OPTION",
              periodUnitCount: 8,
              periodUnit: "MONTH",
              optionOrder: 3,
            },
            {
              periodType: "OPTION",
              periodUnitCount: 1,
              periodUnit: "YEAR",
              optionOrder: 4,
            },
          ],
          tripLocation: "DC",
        },
        {
          durationInDays: 14,
          numberOfTravelers: 20,
          numberOfTrips: 5,
          selectedPeriods: [
            {
              periodType: "OPTION",
              periodUnitCount: 34,
              periodUnit: "WEEK",
              optionOrder: 2,
            },
            {
              periodType: "OPTION",
              periodUnitCount: 8,
              periodUnit: "MONTH",
              optionOrder: 3,
            },
          ],
          tripLocation: "Berlin",
        },
        {
          durationInDays: 14,
          numberOfTravelers: 5,
          numberOfTrips: 10,
          selectedPeriods: [
            {
              periodType: "OPTION",
              periodUnitCount: 34,
              periodUnit: "WEEK",
              optionOrder: 2,
            },
            {
              periodType: "OPTION",
              periodUnitCount: 8,
              periodUnit: "MONTH",
              optionOrder: 3,
            },
            {
              periodType: "OPTION",
              periodUnitCount: 1,
              periodUnit: "YEAR",
              optionOrder: 4,
            },
          ],
          tripLocation: "California",
        },
      ],
    },
    sensitiveInformation: {
      section508Sufficient: true,
      accessibilityReqs508: "",
    },
  },
};

export const sampleIgceRequest = {
  documentType: "INDEPENDENT_GOVERNMENT_COST_ESTIMATE",
  templatePayload: {
    surgeCapabilities: 34,
    fundingDocument: {
      fundingType: "FS_FORM",
      orderNumber: "O2206-097-097-184790",
      gtcNumber: "A2201-097-097-18092",
    },
    contractingShop: {
      name: "DITCO",
    },
    periodsEstimate: [
      {
        period: { periodUnit: "YEAR", periodUnitCount: "1", periodType: "BASE", optionOrder: "" },
        periodLineItems: [
          {
            idiqClin: "x001/x017 Cloud UNCLASSIFIED",
            dowTaskNumber: "4.2.2.1",
            serviceTitle: "Cloud Audit/Monitoring Tools",
            itemDescription: "Monitoring network data",
            unitPrice: 394.38,
            quantity: 1,
            unit: "period",
            contractType: "FFP",
          },
          {
            idiqClin: "x001/x017 Cloud UNCLASSIFIED",
            dowTaskNumber: "4.2.2.2",
            serviceTitle: "Special custom built app - not SNOW",
            itemDescription: "To handle special cases that can not be done in SNOW",
            unitPrice: 799.0,
            quantity: 2,
            unit: "period",
            contractType: "FFP",
          },
        ],
      },
      {
        period: { periodUnit: "WEEK", periodUnitCount: 12, periodType: "OPTION", optionOrder: 2 },
        periodLineItems: [
          {
            idiqClin: "x004/x020 Cloud Support SECRET CLASSIFIED",
            dowTaskNumber: "4.2.2.4",
            serviceTitle: "Application",
            itemDescription: "Basic App ",
            unitPrice: 1200.0,
            quantity: 1,
            unit: "month",
            contractType: "T&M",
          },
          {
            idiqClin: "x001/x017 Cloud UNCLASSIFIED",
            dowTaskNumber: "4.2.2.3",
            serviceTitle: "Application",
            itemDescription: "Staging App",
            unitPrice: 1200.0,
            unit: "months",
            quantity: 10,
            contractType: "FFP",
          },
        ],
      },
    ],
    instructions: {
      estimateDescription: "Through this service, and that service",
      assumptionsMade: "Using this calculator, and years of experience",
      toolsUsed: "List of tools used: calculator service 1, calculator service 2",
      informationSource: "This government agency, that government agency",
      previousEstimateComparison: "Overestimated how much time was needed",
    },
  },
};

export const sampleIfpRequest = {
  documentType: "INCREMENTAL_FUNDING_PLAN",
  templatePayload: {
    requirementsTitle: "Versatile Demo Package",
    missionOwner: "Jewel Heart",
    primaryContact: "Michael Bubble",
    agency: "Department of Agencies",
    organization: "the organization formerly known as organiation",
    financialPoc: "Ester Crest",
    estimatedTaskOrderValue: 125000.55,
    initialAmount: 50000.55,
    remainingAmount: 75000,
    fundingDocument: { fundingType: "FS_FORM", orderNumber: "O-23434-34234" },
    fundingIncrements: [
      { amount: 25000, description: "2nd QTR FY23", order: 1 },
      { amount: 50000, description: "3rd QTR FY23", order: 2 },
    ],
    scheduleText: "Funding Increment #1:\n2nd QTR FY23 - $25,000.00\nFunding Increment #2:\n3rd QTR FY23 - $50,000.00",
    contractNumber: "TBD",
    taskOrderNumber: "TBD",
  },
};

export const fundingDocumentWithMiprNumber = {
  fundingType: "MIPR",
  miprNumber: "M2206-07-077-458790",
};

export const sampleEvalPlanRequest = {
  documentType: "EVALUATION_PLAN",
  templatePayload: {
    taskOrderTitle: "Maria Mission Owner's Eval Plan",
    sourceSelection: "SET_LUMP_SUM",
    method: "BEST_USE",
    standardSpecifications: ["string"],
    customSpecifications: ["string"],
    standardDifferentiators: ["string"],
    customDifferentiators: ["string"],
  },
};

export const sampleRequirementsChecklistRequest = {
  documentType: "REQUIREMENTS_CHECKLIST",
  templatePayload: {
    gtcNumber: "123456",
    projectOverview: {
      title: "Versatile Demo Package",
      scope: "Trying to build up another package that can be used for testing different parts of the system.",
      emergencyDeclaration: true,
    },
    organization: {
      agency: "Defense Information Systems Agency (DISA)",
      name: "Special Div",
    },
    contacts: {
      missionOwnerName: "ADM Jewel Heart IV",
      cor: {
        type: "COR",
        name: "Dak Prescott",
        email: "dak@cowboys.com",
        phoneNumber: "+1 (703) 123-4567, ext. 820",
        dodaac: "aaa999",
      },
      acor: {
        type: "ACOR",
        name: "Yoda",
        email: "yoda@atat.com",
        phoneNumber: "+1 (999) 123-4567, ext. 999",
        dodaac: "bbb888",
      },
      primaryContact: {
        type: "primaryContact",
        name: "Tortellini",
        email: "tortellini@atat.com",
        phoneNumber: "+1 (999) 123-4567, ext. 999",
        dodaac: "ccc888",
      },
    },
    currentContract: [
      {
        currentContractExists: true,
        incumbentContractorName: "Someone Making Decisions",
        contractNumber: "928384",
        taskDeliveryOrderNumber: "29284484",
        contractOrderExpirationDate: "2022-12-09",
      },
      {
        currentContractExists: true,
        incumbentContractorName: "Someone Making Decisions",
        contractNumber: "928375",
        taskDeliveryOrderNumber: "29284463",
        contractOrderExpirationDate: "2021-12-09",
      },
    ],
    exceptionToFairOpportunity: "YES_FAR_16_505_B_2_I_B",
    periodOfPerformance: {
      basePeriod: { periodType: "BASE", periodUnitCount: 1, periodUnit: "YEAR", optionOrder: null },
      optionPeriods: [
        { periodType: "OPTION", periodUnitCount: 36, periodUnit: "WEEK", optionOrder: 4 },
        { periodType: "OPTION", periodUnitCount: 7, periodUnit: "MONTH", optionOrder: 2 },
      ],
      isRequirementFollowOnProcurementSoleSourced: true,
      popStartRequest: true,
      requestedPopStartDate: "2022-11-30",
      timeFrame: "NO_SOONER_THAN",
      recurringRequirement: false,
    },
    contractType: { firmFixedPrice: true, timeAndMaterials: true, justification: "Really need this." },
    sensitiveInformation: {
      baaRequired: true,
      potentialToBeHarmful: true,
      foiaContact: {
        fullName: "Info Protector",
        email: "protector@mail.mil",
        address: "123 FOIA St\nCrystal, VA 22001\nUnited States of America",
      },
      section508: { section508Sufficient: true },
    },
  },
};

export const sampleJustificationAndApprovalRequest = {
  documentType: "JUSTIFICATION_AND_APPROVAL",
  templatePayload: {
    purchaseRequestNumber: "O2208-097-097-697046",
    jwccContractNumber: "HC105023D0002",
    title: "Jeff J&A Test 1",
    scope: "J & A Scope Test 1",
    estimatedValue: 157728,
    estimatedValueFormatted: "$157,728.00",
    agencyLabel: "Business Transformation Agency (BTA)/Jeff Org J&A",
    organizationFullAddress: "123 Fake St\nSpringfield, OH 12345\nUnited States of America",
    contractingShop: "DITCO",
    otherContractingShopFullAddress: null,
    taskOrderType: "firm-fixed-price",
    appropriationFundsType: "Research, Development, Test & Evaluation",
    fundingRequestFiscalYear: "FY23",
    fairOpportunity: {
      proposedVendor: "Google Support Services",
      exceptionToFairOpportunity: "16.505(b)(2)(i)(C)",
      justification: "Jeff J&A Justification 1",
      minimumGovernmentRequirements:
        "The cloud offerings must continue at their current level in order to support...\n\nThese offerings include...\n\nAll my minimum stuff",
      causeOfSoleSourceSituation: "cause of sole source - custom",
      whyCspIsOnlyCapableSource:
        "Google possesses the knowledge, skills, capabilities, certification, clearance, and experience required to continue the program without a break or degradation in critical mission services. Given these critical mission requirements, Google is the only contractor that is capable of performing the necessary services for the DoD within the current required timeline.",
      procurementDiscussion: "google constraints",
      procurementHasExistingEnv: true,
      procurementPreviousImpact:
        "Since there is already an existing environment, the CSP is immediately able to shift to supporting the resultant award associated with this contract action, it would minimize any associated transition costs for the Government. In addition, another contractor would not be positioned to leverage investments made to date to most efficiently meet the objectives of the task order for the anticipated PoP.",
      requirementImpact: "requirement impact details",
      marketResearchDetails: "research details - generated",
      otherFactsToSupportLogicalFollowOn: null,
      plansToRemoveBarriers: "barriers - generated",
    },
    technicalPoc: {
      formalName: "SPC Bob Robert",
      title: "Guy",
      phoneAndExtension: null,
    },
    requirementsPoc: {
      formalName: "GEN Who Where",
      title: null,
      phoneAndExtension: "+1 (223) 300-4293",
    },
    cor: {
      formalName: "GEN Who Where",
      title: null,
      phoneAndExtension: "+1 (223) 300-4293",
    },
    periodOfPerformance: {
      basePeriod: {
        periodType: "BASE",
        periodUnitCount: 12,
        periodUnit: "MONTH",
        optionOrder: 1,
      },
      isRequirementFollowOnProcurementSoleSourced: true,
      optionPeriods: [
        {
          periodType: "OPTION",
          periodUnitCount: 6,
          periodUnit: "MONTH",
          optionOrder: 2,
        },
        {
          periodType: "OPTION",
          periodUnitCount: 6,
          periodUnit: "MONTH",
          optionOrder: 3,
        },
      ],
      popStartRequest: false,
      requestedPopStartDate: "",
      timeFrame: "",
      recurringRequirement: true,
    },
    procurementHistory: [
      {
        contractNumber: "123123132",
        currentContractExists: true,
        contractOrderExpirationDate: "May 31, 2023",
        incumbentContractorName: "Big Incumbent",
        taskDeliveryOrderNumber: "634534543",
        contractOrderStartDate: "December 07, 2022",
        businessSize: "HUBZone",
        competitiveStatus: "Small business (SB) set-aside",
      },
      {
        contractNumber: "284632495436546",
        currentContractExists: true,
        contractOrderExpirationDate: "May 16, 2023",
        incumbentContractorName: "Jeff Incumbent",
        taskDeliveryOrderNumber: "TO32907423",
        contractOrderStartDate: "May 16, 2022",
        businessSize: "Large business",
        competitiveStatus: "Full and open competition",
      },
    ],
  },
};

export const sampleMarketResearchReportRequest = {
  documentType: "MARKET_RESEARCH_REPORT",
  templatePayload: {
    researchers: [
      {
        name: "Jane Researcher",
        title: "Head researcher",
        org: "FEMA",
      },
      {
        name: "John Researcher",
        title: "Assistant researcher",
        org: "FEMA",
      },
    ],
    fairOpportunity: {
      procurementDiscussion: "google constraints",
      procurementPreviousImpact:
        "Since there is already an existing environment, the CSP is immediately able to shift to supporting the resultant award associated with this contract action, it would minimize any associated transition costs for the Government. In addition, another contractor would not be positioned to leverage investments made to date to most efficiently meet the objectives of the task order for the anticipated PoP.",
      marketResearchDetails: "research details - generated",
      causeOfSoleSourceSituation: "cause of sole source - custom",
      procurementHasExistingEnv: true,
      minimumGovernmentRequirements:
        "The cloud offerings must continue at their current level in order to support...\n\nThese offerings include...\n\nAll my minimum stuff",
      plansToRemoveBarriers: "barriers - generated",
      requirementImpact: "requirement impact details",
      exceptionToFairOpportunity: "16.505(b)(2)(i)(B)",
      otherFactsToSupportLogicalFollowOn: null,
      whyCspIsOnlyCapableSource:
        "Google possesses the knowledge, skills, capabilities, certification, clearance, and experience required to continue the program without a break or degradation in critical mission services. Given these critical mission requirements, Google is the only contractor that is capable of performing the necessary services for the DoD within the current required timeline.",
      proposedVendor: "Google Support Services",
      justification: "Jeff J&A Justification 1",
    },
    periodOfPerformance: {
      basePeriod: {
        periodType: "BASE",
        periodUnitCount: 1,
        periodUnit: "YEAR",
        optionOrder: 1,
      },
      isRequirementFollowOnProcurementSoleSourced: true,
      optionPeriods: [
        {
          periodType: "OPTION",
          periodUnitCount: 34,
          periodUnit: "WEEK",
          optionOrder: 2,
        },
        {
          periodType: "OPTION",
          periodUnitCount: 8,
          periodUnit: "MONTH",
          optionOrder: 3,
        },
        {
          periodType: "OPTION",
          periodUnitCount: 1,
          periodUnit: "YEAR",
          optionOrder: 4,
        },
      ],
      popStartRequest: true,
      requestedPopStartDate: "2023-03-01",
      timeFrame: "NO_SOONER_THAN",
      recurringRequirement: false,
    },
    techniquesUsed: [
      {
        technique_value: "PERSONAL_KNOWLEDGE",
        technique_label: "Personal knowledge in procuring supplies/services of this type",
        sequence: 1,
      },
      { technique_value: "DISA_MARKET_RESEARCH_REPO", technique_label: "DISA Market Research Repository", sequence: 2 },
      {
        technique_value: "CONTACT_WITH_KNOWLEDGEABLE_PERSON",
        technique_label: "Contact with knowledgeable persons in Government and industry",
        sequence: 3,
      },
      {
        technique_value: "REVIEW_SIMILAR_RECENT_RESULTS",
        technique_label: "Review of recent market research results for similar or identical supplies/services",
        sequence: 4,
      },
      {
        technique_value: "REVIEW_DATABASES",
        technique_label: "Review of Government and/or commercial databases for relevant information",
        sequence: 5,
      },
      {
        technique_value: "REVIEW_SOURCE_LISTS",
        technique_label: "Review of source lists for identical or similar items obtained",
        sequence: 6,
      },
      {
        technique_value: "REVIEW_PRODUCT_LITERATURE",
        technique_label: "Review of catalogs and/or other generally available product literature",
        sequence: 7,
      },
      {
        technique_value: "REVIEW_OTHER_CONTRACTS",
        technique_label: "Review of existing DISA-wide and other Government-wide Acquisition Contracts",
        sequence: 8,
      },
      { technique_value: "OTHER", technique_label: "Other", sequence: 99 },
    ],
    techniqueOther: "Used an experimental cutting-edge technique for estimation.",
    title: "Jason MRR Test 1",
    estimatedValue: 50000000.0,
    estimatedValueFormatted: "$50,000,000.00",
    summaryOfMarketResearch: "My research details incredible findings from speaking to two leading experts.",
    procurementHistory: [
      {
        contractOrderExpirationDate: "May 16, 2023",
        incumbentContractorName: "Jeff Incumbent 2",
        taskDeliveryOrderNumber: "TO32907423",
        businessSize: "Large business",
        contractNumber: "284632495436546",
        contractOrderStartDate: "May 16, 2022",
        competitiveStatus: "Full and open competition",
        currentContractExists: true,
      },
      {
        contractOrderExpirationDate: "May 15, 2022",
        incumbentContractorName: "Jeff Incumbent 1",
        taskDeliveryOrderNumber: "TO32907422",
        businessSize: "Large business",
        contractNumber: "284632495436545",
        contractOrderStartDate: "May 15, 2021",
        competitiveStatus: "Full and open competition",
        currentContractExists: true,
      },
    ],
    primaryPoc: {
      formalName: "Maria Missionowner",
      phoneAndExtension: "+1 (555) 123-4567",
      title: "Project Lead",
    },
    corPoc: {
      formalName: "Cary Conofficer",
      phoneAndExtension: "+1 (555) 987-6543",
      title: "Contracting Officer",
    },
    agencyLabel: "Business Transformation Agency (BTA)/Some Org",
    researchPersonalKnowledgePersonOrPosition: "Nelly Knowledgeable/Researcher Extraordinaire",
  },
};

export const sampleEvalMemoRequestWithException = {
  documentType: "EVALUATION_MEMO",
  templatePayload: {
    title: "Eval Memo Test",
    estimatedValueFormatted: "$6,299,661.00",
    exceptionToFairOpportunity: true, // EP not generated, expect no EP record
    proposedVendor: "Google Support Services",
    // EP properties below
    taskOrderTitle: null,
    sourceSelection: null,
    method: null,
    standardSpecifications: [],
    customSpecifications: [],
    standardDifferentiators: [],
    customDifferentiators: [],
  },
};

export const sampleEvalMemoRequestWithoutException = {
  ...sampleEvalMemoRequestWithException,
  templatePayload: {
    ...sampleEvalMemoRequestWithException.templatePayload,
    exceptionToFairOpportunity: false, // EP generated, expect EP record
    // EP properties below
    taskOrderTitle: "Amazing Task Order",
    sourceSelection: "NO_TECH_PROPOSAL",
    method: "LPTA",
    standardSpecifications: ["standard spec 1", "standard spec 2", "standard spec 3"],
    customSpecifications: ["custom spec 1", "custom spec 2"],
    standardDifferentiators: ["standard diff 1", "standard diff 2", "standard diff 3"],
    customDifferentiators: ["custom diff 1", "custom diff 2", "custom diff 3"],
  },
};
/* eslint-enable max-len */
