workflow:
  rules:
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event'
    - if: $CI_COMMIT_TAG
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
    - if: $CI_COMMIT_REF_NAME == 'main'

variables:
  FARGATE_TASK_DEFINITION: "nodejs"

default:
  tags:
    - api

stages:
  - verify
  - test
  - sonar
  - synth

assert_package_lock_version:
  stage: verify
  script:
    -   |
      file="package-lock.json"
      expectedVersion="2"
      lockFileVersion="$(jq -r .lockfileVersion "$file")"
      if [ "$lockFileVersion" != "$expectedVersion" ]; then
      echo "$file: lockfileVersion ($lockFileVersion) is invalid (expected: $expectedVersion)"
      exit 1
      else
      echo "$file: lockfileVersion ($lockFileVersion) is the expected value ($expectedVersion)"
      fi

detect_secrets:
  stage: verify
  variables:
    FARGATE_TASK_DEFINITION: "python"
  script:
    -   |
      git ls-files -z | xargs -0 detect-secrets-hook --baseline .secrets.baseline

npm_test:
  stage: test
  cache:
    key: $CI_COMMIT_REF_SLUG
    paths:
      - .npm/
  before_script:
    - npm ci --cache .npm --prefer-offline
  script:
    -   |
      echo "Running tests"
      npm run lint
      npm run build
      npm run test

sonar_scan:
  stage: sonar
  variables:
    SONAR_USER_HOME: "${CI_PROJECT_DIR}/.sonar"
    GIT_DEPTH: "0"
  cache:
    key: "${CI_JOB_NAME}"
    paths:
      - .sonar/cache
  script:
    - sonar-scanner

cdk_synth:
  stage: synth
  cache:
    key: $CI_COMMIT_REF_SLUG
    paths:
      - .npm/
  before_script:
    - npm ci --cache .npm --prefer-offline
  script:
    -   |
      cdk synth \
      -c "atat:EnvironmentId=FullCiTest" \
      -c "atat:VpcCidr=10.250.0.0/16" \
      -c "atat:ApiDomainName=ci.atat.fake.test" \
      -c "atat:ApiCertificateArn=arn:aws:us-east-1:123456789012:certificate/aec3ac93-692e-406e-afef-642fb31afc41" \
      -c "atat:VpcFlowLogBucket=arn:aws:us-east-1:s3::123456789012:flow-logs-123456789012-us-east-1" \
      -c "atat:VersionControlBranch=develop" AtatEnvironmentPipeline/Sandbox
  artifacts:
    paths:
      - cdk.out/*.template.json
      - cdk.out/asset.*/index.js