---
AWSTemplateFormatVersion: "2010-09-09"

Description: >-
  Creates a EventBridge rule for GuardDuty to send an SNS notification with GuardDuty findings.

Parameters:
  pEmailGroup:
    Description: >-
      This is the email distro group that will be notified if a GuardDuty 
      finding(s) triggers an event.
    Type: String


  pKmsKeyId:
    Description: >-
        AWS KMS key used to encrypt the SNS topic.
    Type: String

Resources:
  rEventRule:
    Type: "AWS::Events::Rule"
    Properties:
      Name: "Detect-GuardDuty-Finding"
      Description: "A CloudWatch Event Rule that triggers on Amazon GuardDuty findings. The Event Rule can be used to trigger an SNS notification"
      State: "ENABLED"
      Targets:
        - Arn:
            Ref: "rSnsTopicEventRule"
          Id: "target-sns1"
      EventPattern:
        detail-type:
          - "GuardDuty Finding"
        source:
          - "aws.guardduty"

  rSnsTopicEventRule:
    Type: "AWS::SNS::Topic"
    Properties:
      Subscription:
        - Endpoint: !Ref pEmailGroup #distro email used for dev environment
          Protocol: "email"
      TopicName: "GuardDuty-Event-Rule-Action"
      KmsMasterKeyId: !Ref pKmsKeyId

