import { handler } from "./createPortfolio";
import { ApiGatewayEventParsed } from "../utils/eventHandlingTool";
import { CloudServiceProvider, DodComponent, IPortfolioCreate } from "../../orm/entity/Portfolio";
import { SuccessStatusCode } from "../utils/response";
import { v4 as uuidv4 } from "uuid";
import { Context } from "aws-lambda";
import { ProvisioningStatus } from "../../orm/entity/ProvisionableEntity";

describe("createPortfolio", () => {
  it.skip("successful operation testing locally only", async () => {
    const validRequest: ApiGatewayEventParsed<IPortfolioCreate> = {
      body: {
        name: "Mock Portfolio",
        owner: "jane.manager@example.mil",
        csp: CloudServiceProvider.CSP_A,
        dodComponents: [DodComponent.ARMY, DodComponent.NAVY],
        portfolioManagers: ["joe.manager@example.mil", "jane.manager@example.mil"],
        description: "Mock portfolio description",
        provisioningStatus: ProvisioningStatus.PENDING,
      },
      pathParameters: {
        portfolioId: uuidv4(), // this is required by validateRequestShape, but discarded.  id generated by DB.
      },
      requestContext: { identity: { sourceIp: "7.7.7.7" } },
    } as any;
    const result = await handler(validRequest, {} as Context, () => null);
    expect(result?.statusCode).toBe(SuccessStatusCode.CREATED);
  });
});
