export enum DodComponent {
  AIR_FORCE = "AIR_FORCE",
  ARMY = "ARMY",
  MARINE_CORPS = "MARINE_CORPS",
  NAVY = "NAVY",
  SPACE_FORCE = "SPACE_FORCE",
  COMBATANT_COMMAND = "COMBATANT_COMMAND",
  JOINT_STAFF = "JOINT_STAFF",
  DAFA = "DAFA",
  OSD_PSAS = "OSD_PSAS",
  NSA = "NSA",
}
