AWSTemplateFormatVersion: 2010-09-09
Description: Creating IAM Users via Cloudformation

Parameters:
  Env:
    Description: >-
      The VPC where the Interface Endpoint for SES should be configured.
    Type: String
  CodeCommit:
    Description: >-
      The ARN of the code commit repo.
    Type: String

Resources:
  Gitlabuser:
    Type: AWS::IAM::User  
    Properties:
      UserName: !Sub "Atat-${Env}-Gitlab-user"
      Policies:
      - PolicyName: gitlab-mirroring-access
        PolicyDocument:
          Version: '2012-10-17'
          Statement:
          - Effect: Allow
            Action: 
              - codecommit:GitPull,
              - codecommit:GitPush
            Resource: !Sub "${CodeCommit}"
