---
AWSTemplateFormatVersion: "2010-09-09"

Description: >-
  Creates a CW event to monitor SSO user activity.

Parameters:
  EmailGroup:
      Description: >-
        This is the email group that will be notified of IAM user activity.
      Type: String

  KmsKeyId:
      Description: >-
        Kms key used to encrypt the SNS topic.
      Type: String

Resources:
  IAMuserStatusSnsTopic:
    Type: AWS::SNS::Topic
    Properties:
      TopicName: "IAM-User-Activity-Notification"
      DisplayName: "IAM-User-Activity-Notification"
      KmsMasterKeyId: !Ref KmsKeyId


  IAMuserStatusSnsSubscription:
    Type: AWS::SNS::Subscription
    Properties:
      Endpoint: !Ref EmailGroup
      Protocol: email
      TopicArn: !Ref IAMuserStatusSnsTopic


  CloudWatchSsoSnsStatus:
    Type: AWS::Events::Rule
    Properties: 
      Name: CloudWatchIamUserActivity
      Description: "CW Event to monitor IAM user activity"
      EventPattern: 
        detail-type:
          - AWS API Call via CloudTrail
        source:
          - aws.iam
        detail:
          eventSource:
          - iam.amazonaws.com
          eventName:
          - CreateUser
          - CreateLoginProfile
          - CreateAccessKey
          - UpdateUser
          - UpdateLoginProfile
          - UpdateAccessKey
          - AttachUserPolicy
          - DetachUserPolicy
          - DeleteLoginProfile
          - DeleteUser
      Targets: 
        - Arn: !Ref IAMuserStatusSnsTopic
          Id: "iam-user-activity-notification"