---
name: Run Checks
on:
  push:
    branches: [aws-poc]
  # pull_request:

jobs:
  lint:
    name: Lint code base
    runs-on: ubuntu-20.04
    steps:
      - name: Config NodeJS dependency caching
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
      - name: Setup NodeJS
        uses: actions/setup-node@v2
        with:
          node-version: "14"
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Install CDK
        run: npm install -g aws-cdk
      - name: Install dependencies
        run: npm ci
      - name: Lint Code Base
        uses: github/super-linter@v4
        env:
          DEFAULT_BRANCH: develop
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          LINTER_RULES_PATH: /
          JAVASCRIPT_ES_CONFIG_FILE: .eslintrc.json
          VALIDATE_JAVASCRIPT_ES: true
          VALIDATE_JSON: true
          VALIDATE_TERRAFORM: true
          VALIDATE_YAML: true
          VALIDATE_ALL_CODEBASE: false
          SUPPRESS_POSSUM: true
      - name: Ensure synthesis works
        run:
          cdk synth
