---
AWSTemplateFormatVersion: "2010-09-09"

Description: >-
  Creates a EventBridge rule for GuardDuty to send an SNS notification with GuardDuty findings.

Parameters:
  pEmailGroup:
    Description: >-
      This is the email distro group that will be notified if a GuardDuty 
      finding(s) triggers an event.
    Type: String


  pKmsKeyId:
    Description: >-
        AWS KMS key used to encrypt the SNS topic.
    Type: String

Resources:
  rEventRule:
    Type: "AWS::Events::Rule"
    Properties:
      Name: "cf-iam-user-unused-credentials"
      Description: "A CloudWatch Event Rule that triggers on the non compliance of iam-unused-credentials. The Event Rule can be used to trigger an SNS notification"
      State: "ENABLED"
      Targets:
        - Arn:
            Ref: "rSnsTopicEventRule"
          Id: "target-sns1"
      EventPattern:
        detail-type:
          - "Config Rules Compliance Change"
        source:
          - "aws.config"
        messageType:
          - "ComplianceChangeNotification"
        configRuleName:
          - "iam-user-unused-credentials-check"
        resourceType:
          - "AWS::IAM::User"
        complianceType:
          - "NON_COMPLIANT"
          
  rSnsTopicEventRule:
    Type: "AWS::SNS::Topic"
    Properties:
      Subscription:
        - Endpoint: !Ref pEmailGroup #distro email used for dev environment
          Protocol: "email"
      TopicName: "Config-Rule-Event-Action"
      KmsMasterKeyId: !Ref pKmsKeyId